settings:
  
  dataset:
    name:
    args:
      img_dir: 

    augmentations:
      image_size: [256,256]
      horizontal_flip: 0
      shear: 0
      rotation: 0
      colorjitter:
        brightness: 0
        constrast: 0
        saturation: 0
        hue: 0
      cutout: 0

  model:
    name:
    args:

  backbone:
    name: 
    args: 

  criterion:
    name:
    args:

  metrics:
    - name: 
      args:
    - name:
      args:
      
